### PR TITLE
Fixed signed integer overflow in atoi()

### PR DESCRIPTION
**Pull request by ChristianMoesl**
This is a possible solution for the issue #16. This issue consists of the problems:
1. Signed integer overflow, which is undefined behavior in C99 (problematic when compiling with gcc/clang, etc...)
2. The logic which should handle big decimal numbers

@julian.kanzler (on slack#cc2017) had a nice idea, to avoid integer multiplication, which is hard to check for an potential overflow. So i could come up with this solution.
All overflow checks rely on the following fact: n + c > INT_MAX   ->   n <= INT_MAX - c   (which is used to check for an possible overflow without the danger of an actual overflow).

### CODE REVIEW

**Comment by ChristianMoesl** [comment]
Hmm, seams that the build failed due to a timeout of the travis build machine.

**Comment by ckirsch** [comment]
@ChristianMoesl Let's talk about this next time we meet. Please remind me.

**Comment by ChristianMoesl** [comment]
I totally forgot this pr.. . I'll remind you.

**Comment by ckirsch** [comment]
@ChristianMoesl I just realized that I need this fixed for a paper I am writing. Could you please look into it as soon as you can? Please avoid introducing the `safe` procedures. Instead focus on line 1512 in `selfie.c` on the master branch. Check `n` against `214748363` for all `c` and `214748364` with `c < 8` before computing the next value of `n`. Return `INT_MIN` if `c == 8` and `-1` in all other cases. I hope this avoid any overflows. Otherwise, let me know.

**Comment by ChristianMoesl** [comment]
@ckirsch i'm in holiday atm, so time is limited. But it should be possible to fix this, this week. 

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request closed without merging**
