### PR TITLE
Update grader to show executed commands at all times

### PR DESCRIPTION
**Pull request by CAS-ual-TY**
As suggested in the lecture, someone (me) made the grader spit out what it is executing.
It was already doing that for failed tests, now it does it all the time. Also colored in yellow/orange/gold.

picture

(ignore the lines above the first [PASSED], its my own script I use so I do not have to remember exact assignment identifiers)

### CODE REVIEW

**Comment by CAS-ual-TY** [comment]
Note: print_passed is also called in grade.py on line 16. But this seems to never be called (it also prints "blaaaaa" so I assume it is unused or forgotten about or maybe still indev) so I ignored it.

**Comment by ckirsch** [comment]
@CAS-ual-TY Thanks a lot! This is very nice. How about changing the order: print the command first and then whether it passed or not? Can you do that?

@ChristianMoesl What do you think about this? Also, please check out the "blaaaa" print :) I guess we don't need that anymore.

**Comment by CAS-ual-TY** [comment]
@ckirsch Done and committed. I had to slightly expand the current model to gain access to the executed command (before it is actually executed).

picture

**Comment by CAS-ual-TY** [comment]
Another alternative formatting suggestion:

picture

**Comment by ckirsch** [comment]
@CAS-ual-TY Even better.

**Review by ChristianMoesl — APPROVED** [review]
Looks good to me! 🚀

**Comment by ckirsch** [comment]
@ChristianMoesl What about the `blaaa` in the grader somewhere? Could you please fix that?

**Pull request merged**
