### PR TITLE
docs: add bachelor thesis by Nadir Fejzić

### PR DESCRIPTION
**Pull request by nfejzic**
In this PR my bachelor thesis alongside with developed tool **peRISCope** is added. 

As far as I can tell, I cannot create a release, so for now I simply added the link to selfie repository. If I need to link to a specific release (would probably be nicer), then I'd need some help.

### CODE REVIEW

**Comment by ckirsch** [comment]
@nfejzic how about creating a tag?

**Comment by nfejzic** [comment]
> @nfejzic how about creating a tag?

@ckirsch I don't have the permission to push tag directly to the main repository. However, I rebased my commits into a single commit, changed the link in readme to point to the (expected) URL of release, and added a tag to latest commit. Merging the commit should (hopefully) also merge the tag.

**Comment by ckirsch** [comment]
Sounds great. Please check if it works.

**Comment by nfejzic** [comment]
> Sounds great. Please check if it works.

Unfortunately it wasn't the case. If you have time (or someone else who has push access to the repo) it would be nice if you can quickly do it. Basically just: 

```sh
git clone https://github.com/cksystemsteaching/selfie # skip if already cloned
cd selfie # skip if already in selfie directory
git checkout main && git pull
git tag bachelor_thesis_fejzic c0165b9e # tags the given commit
git push --tags # upload tags to Github
```

**Pull request merged**
