### PR TITLE
README.md: Add missing link target.

### PR DESCRIPTION
**Pull request by cznic**
Fixes a minor issue.

### CODE REVIEW

**Comment by cznic** [comment]
@ckirsch Gentle ping.

**Comment by ckirsch** [comment]
@cznic `[http://selfie.cs.uni-salzburg.at]()` is short for `[http://selfie.cs.uni-salzburg.at](http://selfie.cs.uni-salzburg.at)`

**Comment by cznic** [comment]
@ckirsch 

> [http://selfie.cs.uni-salzburg.at]() is short for [http://selfie.cs.uni-salzburg.at](http://selfie.cs.uni-salzburg.at)

Not at Github's domain:

image

Also, you may want to try to clik the first link in this comment.

**Comment by ckirsch** [comment]
True! Please reopen the PR but make sure to avoid changing anything but the actual issue (do not add a linefeed at the end, for example). Thanks!

**Pull request closed without merging**
